name: Generate artifacts

on:
  push:
    paths:
      - 'src/**.md'
  workflow_dispatch:

jobs:
  generateFiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make install
      - run: make build
      - run: |
         cd ci
         ls
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          title: 'Automatic generation of artifacts'
          body: 'New files have been generated'
      
      
